Added native theme and titlebar support , TITLEBAR SUPPORT ONLY WORKS ON WINDOWS!!!!!!!!!!!!!!!!!!!!!!!!!!!
rdbende/Sun-Valley-ttk-theme pull request #132
Opened 2024-03-27 23:32 UTC by jhi2

**IMPORTANT: TITLEBAR SUPPORT USES WINDOWS RUNTIMES AND FEATURES THEREFORE MAKING IT WINDOWS-ONLY!**
Requires darkdetect for native theme support

2024-03-27 23:35 UTC, jhi2 commented on sv_ttk/__init__.py
> +def titlebar(root: tkinter.tk,theme: "light"):
**IMPORTANT: TITLEBAR SUPPORT ONLY WORKS ON WINDOWS!!!!!!!!!!!!!!!!!!!!!!!!!!!**

2024-03-27 23:36 UTC, jhi2 commented on sv_ttk/__init__.py
> +def native_theme(root:tkinter.tk):
**NATIVE THEME SUPPORT INCLUDES TITLEBAR SUPPORT THUS MAKING IT WINDOWS-ONLY!!!!!!**

2024-03-27 23:39 UTC, jhi2 commented on sv_ttk/__init__.py
> +import darkdetect
**PACKAGE INSTALL REQUIRED**

2024-03-28 00:26 UTC, jhi2 commented on sv_ttk/__init__.py
> +def titlebar(root: tkinter.tk,theme):
**TITLEBAR SUPPORT USES WINDOWS FEATURES, THUS MAKING IT WINDOWS-ONLY **

2024-03-28 01:29 UTC, jhi2 commented
REALLY COOL! run uploadtopypi/upload.py to upload it to pypi

2024-03-29 21:11 UTC, jhi2 commented
FYI: I based this off my fork on pypi

2024-03-31 10:09 UTC, rdbende requested changes
Hi!
I don't understand what's your goal here. Is this a personal fork of the project and which you accidentally made a PR for, or do you want me to merge this?
If the latter is the case, then I have a few comments, because I'm not going to merge this as is.

1. I don't want do depend on neither `darkdetect` nor `pillow`. There's a reason why there's no function for setting the system theme, if people need it, they can always pass in the result provided by `darkdetect.theme()`. Pillow isn't needed either, because Tkinter is able to load PNG images by default.
2. Don't use `os.system`. If you really want to call shell commands, then use `subprocess.call` or `subprocess.Popen` depending on your needs, but in this case it's really isn't needed. If you need to install a dependency, put it in `requirements.txt` or `pyproject.toml`, but never use a `pip install` call, because people might not have pip installed at all, and that will make the whole package unable to load.
3. Speaking of pip, I already have (or just **had**, because you deleted it) an automated script, that uploads the package to Pypi, so there's no need to introduce a Python script for that. And btw, you exposed your Pypi token. Generate a new one ASAP, because now anyone is able to upload packages to your account using it. **NEVER EVER COMMIT SUCH THINGS TO VERSION CONTROL!!!**
4. Also, please don't restructure the whole project. I'm happy with the current structure, and I don't need new directories, unnecessary files, or a rewritten README. Adding _"This is a pull request based off of sv-ttk theme by rdbende"_ is pointless, because when it is merged into main, it will be completely irrelevant whose project this particular PR was based upon, and it will be clear that I am the project owner.
5. Those cool messageboxes are not littlewhitecould's, but they were written by me. I want to include that code in this package eventually, but it's incomplete, that's why it lives in [this separate repo](https://github.com/rdbende/Sun-Valley-messageboxes)
6. Don't change the licence file. It doesn't need to include all contributors, and especially don't overwrite my email address, unless you want to get that many support emails that I get :D
7. If you revert this PR to just adding the dark mode titlebars feature, I think it's fine, but please don't comment about how Windows-only it is, but simply add am `if sys.platform == "win32"`, to make it sure, that it will run only on Window. Additionally, you will need to add an attribution to the [original code source and author](https://gist.github.com/Olikonsti/879edbf69b801d8519bf25e804cec0aa) on the top of the file.

2024-04-04 07:57 UTC, closed without merging

2024-04-04 22:33 UTC, jhi2 commented
Try this